# Generated by Django 3.1.4 on 2020-12-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='anon', max_length=25),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='anon', max_length=25),
        ),
    ]
